### ISSUE TITLE
Beast Mode

### ISSUE THREAD

**Issue by blackearth2014** [NikolaiVChr/Autinn#3]
Nikolai,

You are in beast mode development. I have just missed 2 updates you have put out.

Good Job

**Comment by NikolaiVChr** [comment]
Maybe too fast, I just improved a couple of modules, should maybe have waited a couple of days with last update. :)

**Comment by blackearth2014** [comment]
Nah dude, do you. Don’t hinder your creativity because folks missed some updates. Just keep flying to the sky.

This is your season
Omar Brown
Blessed House Media

On Jan 23, 2018, at 7:26 PM, Nikolai V. Chr. <notifications@github.com> wrote:

Maybe too fast, I just improved a couple of modules, should maybe have waited a couple of days with last update. :)

**Comment by NikolaiVChr** [comment]
What I meant was that I do not want to bother the Rack repo with my updates too often.
Anyway thank for you supporting comment. :)
Closing this issue for now.
