### ISSUE TITLE
MAC release?

### ISSUE THREAD

**Issue by antoniograzioli** [NikolaiVChr/Autinn#4]
Hi, I see no MAC release, I can help you and compile it for Mac if you send me the code :-)

**Comment by NikolaiVChr** [comment]
At some point I will certainly want to have a mac release.
I will consider that, thank you for the offer. :)

**Comment by lnikj** [comment]
Hi Nikolai. Lots of mac users would love to see a Mac release. Please take Antonio up on his offer. Many thanks.

**Comment by NikolaiVChr** [comment]
Alright Antonio, I will use the contact form on your Autodafe website, to send you my e-mail address.
Thanks again. :)

**Comment by antoniograzioli** [comment]
Hi sorry, I have been away for work for some days. Will try to catch up ASAP

**Comment by NikolaiVChr** [comment]
Fixed. Thanks.
